/* eslint-disable @next/next/no-img-element */
"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { categories, type Category } from "@/db/schema";
import type { Card } from "@/lib/types";
import type { ParsedReceipt } from "@/lib/ocr/parser";

export function ReceiptForm({ photo, preview, initial, rawOcrText, onStartOver }: { photo: Blob; preview: string; initial: ParsedReceipt; rawOcrText: string; onStartOver: () => void }) {
  const router = useRouter(); const [merchant, setMerchant] = useState(initial.merchant); const [amount, setAmount] = useState(initial.amount); const [date, setDate] = useState(initial.date); const [category, setCategory] = useState<Category>("Other"); const [cardId, setCardId] = useState(""); const [cards, setCards] = useState<Card[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/cards").then((r) => r.ok ? r.json() : []).then((items: Card[]) => { setCards(items); const match = items.find((card) => card.lastFour === initial.cardLastFour); if (match) setCardId(match.id); }); }, [initial.cardLastFour]);
  useEffect(() => { const timer = setTimeout(() => { if (merchant.trim().length > 1) fetch(`/api/merchant-rule?merchant=${encodeURIComponent(merchant)}`).then((r) => r.json()).then((data) => { if (data.category) setCategory(data.category); }).catch(() => undefined); }, 400); return () => clearTimeout(timer); }, [merchant]);
  async function save(event: React.FormEvent) {
    event.preventDefault(); setError(""); setSaving(true); const form = new FormData(); form.set("image", photo, "receipt.jpg"); form.set("merchant", merchant); form.set("amount", amount); form.set("date", date); form.set("cardId", cardId); form.set("category", category); form.set("rawOcrText", rawOcrText);
    try { const response = await fetch("/api/receipts", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push(`/transactions/${data.id}?saved=1`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The receipt couldn't be saved."); setSaving(false); }
  }
  return <form className="receipt-review" onSubmit={save}><aside className="receipt-preview"><img src={preview} alt="Receipt selected for review" /><button type="button" className="text-button" onClick={onStartOver}>Choose a different photo</button></aside><section className="form-card"><div className="review-note"><span>✓</span><p><strong>Receipt read successfully</strong><br />Review each field before saving.</p></div><label>Merchant<input value={merchant} onChange={(e) => setMerchant(e.target.value)} placeholder="Store name" required autoFocus /></label><div className="form-row"><label>Amount<span className="money-input"><b>$</b><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^\d.]/g, ""))} placeholder="0.00" required /></span></label><label>Purchase date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label></div><label>Card<select value={cardId} onChange={(e) => setCardId(e.target.value)}><option value="">Card not identified</option>{cards.map((card) => <option key={card.id} value={card.id}>{card.name} •{card.lastFour}</option>)}</select>{initial.cardLastFour && !cards.some((card) => card.lastFour === initial.cardLastFour) && <small>Receipt shows a card ending in {initial.cardLastFour}. Add it in Cards later.</small>}</label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value as Category)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label>{error && <div className="notice error">{error}</div>}<button className="button primary save-button" disabled={saving}>{saving ? "Saving…" : "Save Receipt"}</button></section></form>;
}
