"use client";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { Receipt } from "@/lib/types";
import { formatMoney } from "@/lib/utils/format";
import { PageHeader } from "./PageHeader";

function totalsBy(receipts: Receipt[], key: (receipt: Receipt) => string) {
  return Object.entries(receipts.reduce<Record<string, number>>((all, receipt) => { const label = key(receipt); all[label] = (all[label] ?? 0) + Number(receipt.amount); return all; }, {})).sort((a, b) => b[1] - a[1]);
}
function Breakdown({ title, rows }: { title: string; rows: [string, number][] }) {
  const max = rows[0]?.[1] || 1; return <article className="breakdown-card"><h3>{title}</h3>{rows.length ? <div className="breakdown-list">{rows.map(([name, value]) => <div key={name}><p><span>{name}</span><strong>{formatMoney(value)}</strong></p><div className="mini-bar"><span style={{ width: `${Math.max(4, value / max * 100)}%` }} /></div></div>)}</div> : <p className="muted">No spending in this period.</p>}</article>;
}
export function Reports() {
  const now = new Date(); const [view, setView] = useState<"monthly" | "yearly">("monthly"); const [receipts, setReceipts] = useState<Receipt[]>([]); const [month, setMonth] = useState(now.getMonth()); const [year, setYear] = useState(now.getFullYear());
  useEffect(() => { fetch("/api/receipts").then((r) => r.json()).then(setReceipts); }, []);
  const years = [...new Set([now.getFullYear(), ...receipts.map((r) => new Date(r.transactionDate).getFullYear())])].sort((a, b) => b - a);
  const period = receipts.filter((receipt) => { const date = new Date(receipt.transactionDate); return date.getFullYear() === year && (view === "yearly" || date.getMonth() === month); });
  const total = period.reduce((sum, receipt) => sum + Number(receipt.amount), 0); const byCategory = totalsBy(period, (r) => r.category); const byCard = totalsBy(period, (r) => r.cardName ? `${r.cardName} •${r.cardLastFour}` : "No card"); const byMerchant = totalsBy(period, (r) => r.merchant);
  const monthly = Array.from({ length: 12 }, (_, index) => ({ name: new Date(2024, index).toLocaleString("en-US", { month: "short" }), total: receipts.filter((r) => { const d = new Date(r.transactionDate); return d.getFullYear() === year && d.getMonth() === index; }).reduce((sum, r) => sum + Number(r.amount), 0) }));
  const highest = monthly.reduce((best, item) => item.total > best.total ? item : best, monthly[0]);
  return <div><PageHeader eyebrow="Spending overview" title="Reports" description="A clear look at where your money went." /><div className="report-toolbar"><div className="segment"><button onClick={() => setView("monthly")} className={view === "monthly" ? "active" : ""}>Monthly</button><button onClick={() => setView("yearly")} className={view === "yearly" ? "active" : ""}>Yearly</button></div><div className="period-selectors">{view === "monthly" && <select aria-label="Month" value={month} onChange={(e) => setMonth(Number(e.target.value))}>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i}>{new Date(2024, i).toLocaleString("en-US", { month: "long" })}</option>)}</select>}<select aria-label="Year" value={year} onChange={(e) => setYear(Number(e.target.value))}>{years.map((item) => <option key={item}>{item}</option>)}</select></div></div><section className="report-hero"><p>{view === "monthly" ? new Date(year, month).toLocaleString("en-US", { month: "long", year: "numeric" }) : year}</p><strong>{formatMoney(total)}</strong><span>{period.length} {period.length === 1 ? "transaction" : "transactions"}</span></section>{view === "yearly" && <><div className="report-stats"><div><span>Monthly average</span><strong>{formatMoney(total / 12)}</strong></div><div><span>Highest month</span><strong>{highest.total ? `${highest.name} · ${formatMoney(highest.total)}` : "—"}</strong></div></div><section className="chart-card"><h2>Spending by month</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly} margin={{ top: 16, right: 8, left: -15, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e6e8e4" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} tickFormatter={(v) => `$${v}`} /><Tooltip formatter={(value) => formatMoney(Number(value))} cursor={{ fill: "#f4f6f2" }} /><Bar dataKey="total" fill="#27745b" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></section></>}<div className="breakdown-grid"><Breakdown title="By category" rows={byCategory} /><Breakdown title="By card" rows={byCard} /><Breakdown title="Top merchants" rows={byMerchant.slice(0, 6)} /></div></div>;
}
